config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :static_pages, only: [:index]
  # Defines the root path route ("/")
  # root "articles#index"
  root 'static_pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    @flickr = Flickr.new
    @flickr_user_id = params[:flickr_user_id]
    @photos =
      if params[:get_recent]
        @flickr.photos.getRecent(per_page: 20)
      elsif !@flickr_user_id.blank?
        flickr_user_photos
      end
  end

  private

  def flickr_user_photos
    @flickr.photos.search(user_id: @flickr_user_id)
  rescue Flickr::FailedResponse
    flash.now[:flickr_user_error] = 'Invalid user ID!'
    nil
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flickr Photo Feed</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/index.html.erb
<p>Type the ID of a Flickr user to see their photos.</p>
<p>The Flickr User ID can be found by navigating to the “You” page on Flickr.
The ID is the string found after <code>https://www.flickr.com/photos/</code> on the “You” page.
For example, <code>196350904@N06</code>.
</p>
<%= form_with method: :get do |form| %>
  <%= form.label :flickr_user_id, 'Flickr User ID:'%>
  <%= form.text_field :flickr_user_id, value: @flickr_user_id %>
  <%= form.submit 'See Photos' %>
  <%= flash[:flickr_user_error] %>
<% end %>

<p>Alternatively: <%= link_to 'See Random Recent Photos from Flickr', static_pages_path(get_recent: true) %></p>

<% if @photos %>
  <div class="photo-with-arrows">
    <div class="arrow previous hidden-with-space"><</div>
    <div class="photos">
      <% @photos.each_with_index do |photo, i| %>
        <div class="photo <%= i == 0 ? '' : 'hidden' %>" id="photo<%= i %>">
          <%= image_tag Flickr.url(photo) %>
        </div>
      <% end %>
    </div>
    <div class="arrow next <%= @photos.length == 1 ? 'hidden' : '' %>">></div>
  </div>
<% end %>